/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Insert_Update_Delete_ComboBox;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class EmployeeView extends javax.swing.JFrame {

    /**
     * Creates new form EmployeeView
     */
    public EmployeeView() {
        initComponents();
        new EmployeeDaoImp().createTable();
        displayDataIntoComboBox();
        displayDataIntoTable();

    }

    public void displayDataIntoComboBox() {
//        EmployeeDaoImp empDao = new EmployeeDaoImp();
//        List<Employee> e = empDao.getEmployeesRole();
//        jComboBoxRolesInDB.addItem("Select A Role");
//        for (Employee em : e) {
//            jComboBoxRolesInDB.addItem(em.getRole());
//        }
        EmployeeDaoImp empDao = new EmployeeDaoImp();
        List<Employee> list = empDao.getEmployeesRole();
        jComboBoxRolesInDB.addItem("Select A Role");
        for (Employee e : list) {
            jComboBoxRolesInDB.addItem(e.getRole());
        }
    }

    public void displayDataIntoTable() {
        clearTable();
        EmployeeDao employeeDao = new EmployeeDaoImp();
        DefaultTableModel model = (DefaultTableModel) jTableDisplay.getModel();
        List<Employee> list = employeeDao.getEmployees();
        Object cols[] = new Object[3];
        for (int i = 0; i < list.size(); i++) {
            cols[0] = list.get(i).getId();
            cols[1] = list.get(i).getName();
            cols[2] = list.get(i).getRole();
            model.addRow(cols);
        }
    }

    public void clearTable() {
        DefaultTableModel model = (DefaultTableModel) jTableDisplay.getModel();
        model.setRowCount(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDisplay = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldId = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldRole = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButtonUpdate = new javax.swing.JButton();
        jButtonInsert1 = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jButtonExit = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jComboBoxRolesInDB = new javax.swing.JComboBox<>();
        jTextFieldName = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTableDisplay.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Name", "Role"
            }
        ));
        jTableDisplay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableDisplayMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableDisplay);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Employee Form");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("ID:");

        jTextFieldId.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Name:");

        jTextFieldRole.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Role:");

        jButtonUpdate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonUpdate.setText("Update");
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });

        jButtonInsert1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonInsert1.setText("Insert");
        jButtonInsert1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInsert1ActionPerformed(evt);
            }
        });

        jButtonDelete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonDelete.setText("Delete");
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });

        jButtonExit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonExit.setText("Exit");
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Roles In Database:");

        jComboBoxRolesInDB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBoxRolesInDB.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxRolesInDBItemStateChanged(evt);
            }
        });
        jComboBoxRolesInDB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxRolesInDBActionPerformed(evt);
            }
        });

        jTextFieldName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(119, 119, 119)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldRole, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                                    .addComponent(jComboBoxRolesInDB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextFieldName, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jButtonInsert1)
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonExit)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButtonUpdate)
                                        .addGap(31, 31, 31)
                                        .addComponent(jButtonDelete))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(301, 301, 301)
                                .addComponent(jLabel1)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(24, 24, 24)
                                .addComponent(jLabel5))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBoxRolesInDB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonUpdate)
                    .addComponent(jButtonInsert1)
                    .addComponent(jButtonDelete))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                .addComponent(jButtonExit)
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButtonExitActionPerformed

    private void jButtonInsert1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInsert1ActionPerformed
//fields
        int id = Integer.parseInt(jTextFieldId.getText().trim());
        String name = jTextFieldName.getText().trim();
        String role = jTextFieldRole.getText().trim();
        //validation
        if (jTextFieldId.getText().trim().length() < 3) {
            JOptionPane.showMessageDialog(null, "Id should be atleast 3 characters!");
        } else if (name.length() < 4) {
            JOptionPane.showMessageDialog(null, "Name should be atleast 4 characters!");

        } else if (role.length() < 5) {
            JOptionPane.showMessageDialog(null, "Role  should be atleast 5 characters!");

        } else {

            EmployeeDao employeeDao = new EmployeeDaoImp();
            ///
            try {
                Employee exitEmployee = employeeDao.getEmployeeById(id);
                if (exitEmployee.getName() != null) {
                    JOptionPane.showMessageDialog(null, "Id Already exists!");

                } else {
                    Employee emp = new Employee(id, name, role);
                    employeeDao.insert(emp);
                    displayDataIntoTable();
                    JOptionPane.showMessageDialog(null, "Data successfully inserted into employee table!");
                }
            } catch (Exception e) {
                Employee emp = new Employee(id, name, role);
                employeeDao.insert(emp);
                displayDataIntoTable();
                JOptionPane.showMessageDialog(null, "Data successfully inserted into employee table!");

            }
            displayDataIntoComboBox();

        }

        //inser to the database
        //display into the table

    }//GEN-LAST:event_jButtonInsert1ActionPerformed

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed
        EmployeeDao empDao = new EmployeeDaoImp();
        try {
            Employee empCheck = empDao.getEmployeeById(selectedId);
            if (empCheck.getName() != null) {
                Employee emp = new Employee(selectedId, jTextFieldName.getText().trim(), jTextFieldRole.getText().trim());
                empDao.update(emp);
                displayDataIntoTable();
                JOptionPane.showMessageDialog(null, "Data successfully udpated for id: " + selectedId + " into employee table!");

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Please Enter data to update!");

        }


    }//GEN-LAST:event_jButtonUpdateActionPerformed
    private int selectedId;
    private void jTableDisplayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableDisplayMouseClicked
        DefaultTableModel model = (DefaultTableModel) jTableDisplay.getModel();
        int i = jTableDisplay.getSelectedRow();
        jTextFieldId.setText(model.getValueAt(i, 0).toString().trim());
        jTextFieldName.setText(model.getValueAt(i, 1).toString().trim());
        jTextFieldRole.setText(model.getValueAt(i, 2).toString().trim());
        ///select the id for update and delete
        selectedId = Integer.parseInt(model.getValueAt(i, 0).toString().trim());
    }//GEN-LAST:event_jTableDisplayMouseClicked

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        // TODO add your handling code here:
        EmployeeDao empDao = new EmployeeDaoImp();
        Employee emp = empDao.getEmployeeById(selectedId);
        try {
            if (emp.getName() != null) {
                empDao.delete(emp);
                displayDataIntoTable();
                jTextFieldId.setText("");
                jTextFieldName.setText("");
                jTextFieldRole.setText("");
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jComboBoxRolesInDBItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxRolesInDBItemStateChanged
//        clearTable();
//        EmployeeDaoImp employeeDao = new EmployeeDaoImp();
//        DefaultTableModel model = (DefaultTableModel) jTableDisplay.getModel();
//        List<Employee> list = employeeDao.getEmployeesbyRole(jComboBoxRolesInDB.getSelectedItem().toString().trim());
//        Object cols[] = new Object[3];
//        for (int i = 0; i < list.size(); i++) {
//            cols[0] = list.get(i).getId();
//            cols[1] = list.get(i).getName();
//            cols[2] = list.get(i).getRole();
//            model.addRow(cols);
//        }
        clearTable();
        EmployeeDaoImp empDao = new EmployeeDaoImp();
        DefaultTableModel model = (DefaultTableModel) jTableDisplay.getModel();
        List<Employee> list = empDao.getEmployeesbyRole(jComboBoxRolesInDB.getSelectedItem().toString().trim());
        Object cols[] = new Object[3];
        for (int i = 0; i < list.size(); i++) {
            cols[0] = list.get(i).getId();
            cols[1] = list.get(i).getName();
            cols[2] = list.get(i).getRole();
            model.addRow(cols);
        }
    }//GEN-LAST:event_jComboBoxRolesInDBItemStateChanged

    private void jComboBoxRolesInDBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxRolesInDBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxRolesInDBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonInsert1;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JComboBox<String> jComboBoxRolesInDB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableDisplay;
    private javax.swing.JTextField jTextFieldId;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldRole;
    // End of variables declaration//GEN-END:variables
}
