/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package swing.MySqlDemo.Table.Demo.service.StudentView;

import javax.swing.JOptionPane;

/**
 *
 * @author Student- J2EE
 */
public class Demo extends javax.swing.JPanel {

    /**
     * Creates new form Demo
     */
    public Demo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        lbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        texFild = new javax.swing.JTextArea();
        ldl = new javax.swing.JButton();
        update = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        idtex = new javax.swing.JTextField();
        ibl = new javax.swing.JLabel();
        serch = new javax.swing.JToggleButton();

        jLabel2.setText("jLabel2");

        jButton1.setText("jButton1");

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 255, 153));
        jLabel1.setText("Student Info");

        lbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl.setText("Student Name :");

        texFild.setColumns(20);
        texFild.setRows(5);
        jScrollPane1.setViewportView(texFild);

        ldl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ldl.setForeground(new java.awt.Color(0, 255, 255));
        ldl.setText("Start");
        ldl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ldlActionPerformed(evt);
            }
        });

        update.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        update.setForeground(new java.awt.Color(255, 0, 255));
        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        delete.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        delete.setForeground(new java.awt.Color(255, 0, 51));
        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        ibl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ibl.setForeground(new java.awt.Color(255, 0, 0));
        ibl.setText("ID  :");

        serch.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        serch.setForeground(new java.awt.Color(0, 0, 102));
        serch.setText("Serch");
        serch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(33, 33, 33)
                            .addComponent(ldl)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(update)
                            .addGap(30, 30, 30)
                            .addComponent(delete))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(47, 47, 47)
                            .addComponent(jLabel1))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(ibl)
                                    .addGap(18, 18, 18)
                                    .addComponent(idtex)
                                    .addGap(18, 18, 18)
                                    .addComponent(serch))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lbl)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(idtex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(serch, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(ibl, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ldl)
                    .addComponent(update)
                    .addComponent(delete))
                .addContainerGap(50, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ldlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ldlActionPerformed
        // TODO add your handling code here:

        Student student = new Student();
        if (texName.getText().trim().length() > 3) {

            student.setName(textName.getText());

            CommonDAO obj = new StudentService();

            obj.save(student);
            ldlMsg.setText("Successfully save");
        } else {
            JOptinPane.showMessageDialog(null, "Insert valid name")
        }
    }//GEN-LAST:event_ldlActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:

        CommonDAO obj
        
        
    }//GEN-LAST:event_updateActionPerformed

    private void serchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serchActionPerformed
        // TODO add your handling code here:
        CommonDAO obj = new StudentService();

        if (txtID.getTex().length() == 0) {
            JOptionPane.showConfirmDialog(null, "Name An Student ID")
        } else {

            Student student = obj.getById(Integer.parseInt(textID, getText()));
            txtName.setText(student.getName());
        }
    }//GEN-LAST:event_serchActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        CommonDAO obj = new StudentService();
        obj.deleteById(Integer.parseInt("tex.ID))

        if (txtID.getTex().length() == 0) {
            JOptionPane.showConfirmDialog(null, "Delate An students id");

        } else {

        }

    }//GEN-LAST:event_deleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton delete;
    private javax.swing.JLabel ibl;
    private javax.swing.JTextField idtex;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lbl;
    private javax.swing.JButton ldl;
    private javax.swing.JToggleButton serch;
    private javax.swing.JTextArea texFild;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
